name: CI Pipeline

on:
  push:
    branch: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v4


      - name: Build Docker image
        run: docker build -t devops-app ./api


      - name: Run container
        run: docker run -d -p 8000:8000 devops-app


      - name: Wait for container
        run: sleep 3

      - name: Check API
        run: curl http://localhost:8000
