name: CI Pipeline

on:
  push:
    branch: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v4


      - name: Build Docker image
        run: docker build -t devops-app ./api


      - name: Run container
        run: docker run -d -p 8000:8000 devops-app


      - name: Wait for container
        run: sleep 3

      - name: Create env file
        run: echo "API_PORT=8000" > .env

      - name: Create secret file
        run: echo "testpassword" > db_password.txt

      - name: Check API
        run: |
          for i in {1..5}; do
            if curl -sf http://localhost:8000 > /dev/null; then
              echo "API is up"
              exit 0
            fi
            sleep 1
          done
          exit 1

      - name: Show API health logs
        run: docker compose logs api

      - name: Check API heath simple
        run: docker compose ps

      - name: Wait for API healthy
        run: |
          for i in {1..10}; do
             STATUS=$(docker compose ps --format json | jq -r '.[] | select(.Service=="api") | .Health')
             if [ "$STATUS" ="healthy" ]; then
              echo "API is healthy"
              exit 0
            fi
            sleep 2
          done
          echo "API not healthy"
          exit 1

      - name: Run docker compose
        run: docker compose up -d

      - name: Wait for nginx
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8085 > /dev/null; then
              echo "Nginx is up"
              exit 0
            fi
            echo "Waiting..."
            sleep 2
          done
          echo "Nginx failed to start"
          exit 1

      - name: Debug containers
        run: docker ps -a

      - name: Debug nginx logs
        run: docker compose logs nginx

      - name: Check nginx
        run: curl http://localhost:8085
