name: CI Pipeline

on:
  push:
    branch: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v4


      - name: Build Docker image
        run: docker build -t devops-app ./api


      - name: Run container
        run: docker run -d -p 8000:8000 devops-app


      - name: Wait for container
        run: sleep 3

      - name: Check API
        run: curl http://localhost:8000

      - name: Create env file
        run: echo "API_PORT=8000" > .env

      - name: Create secret file
        run: echo "testpassword" > db_password.txt

      - name: Run docker compose
        run: docker compose up -d

      - name: Wait for services
        run: sleep 10

      - name: Debug containers
        run: docker ps -a

      - name: Debug nginx logs
        run: docker logs nginx

      - name: Check nginx
        run: curl http://localhost:8085
